### ISSUE TITLE
Wordwrap option?

### ISSUE THREAD

**Issue by lintalist** [G33kDude/RichCode.ahk#2]
Would it possible to add a word wrap option to the settings? 

<pre>
Settings :=
( LTrim Join Comments
{
	"TabSize": 4,
	"Indent": "`t",
	<b>"WordWrap": true,</b>
....
</pre>

I think this would be useful to have.

**Comment by G33kDude** [comment]
Thanks for the contribution!

**Comment by lintalist** [comment]
No problem, glad you liked it. I will be using RichCode in Lintalist in the near future. I was pleasantly surprised how easy it was to incorporate and replace a standard edit control :-)
