### ISSUE TITLE
Crash on paste when using v1.1.27.01 (doesn't happen with v1.1.26.01) ?

### ISSUE THREAD

**Issue by lintalist** [G33kDude/RichCode.ahk#5]
Not sure what is going on but I just upgraded to AHK v1.1.27.01, unicode, and when I paste text in a RichCode control "AutoHotkey stops working" and it crashes. But when I run it using v1.1.26.01 pasting text is no problem.

Is it just my system or do you experience this as well (just paste some text into 'demo')

Edit: Also seems to crashing when pressing the TAB key ? text text TAB -> crash

**Comment by G33kDude** [comment]
I am also experiencing this issue. It appears that v1.1.27.01 introduces a bug into AHK, a report for which has been filed [here](https://autohotkey.com/boards/viewtopic.php?f=14&t=42202).

For now, I suggest not using 1.1.27.01 with RichCode.ahk, but if you think there is enough demand I can update it to work around the bug.

**Comment by lintalist** [comment]
Thanks for looking into it. I'm sure it will be fixed in AutoHotkey 1.1.27.02 so no need for a work around.

**Comment by G33kDude** [comment]
Fixed in AHK 1.1.27.02
